[package]
name = "face-cropper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
image = "0.24.6"
indicatif = "0.17.11"
rust-faces = { version = "1.0.0", features = ["viz"] }
